name: eazy_swipeable_cards
description: "A new Flutter package that helps creating a stack of swipeable cards."
version: 1.0.0
homepage: "https://oussama-maatallah.web.app/blog/swipeable-cards"
repository: https://github.com/melwiss/swipeable_cards

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
